import { NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";
import { askEngine, parseJsonResponse } from "@/lib/claude";
import { todayISO } from "@/lib/dates";

interface PlannedSession {
  type: "fuerza" | "running" | "yoga" | "otro";
  week_number: number;
  exercises: Array<{ name: string; sets?: number; reps?: string; notes?: string }>;
  justification: string;
}

interface CheckIn {
  energy: number; // 1-5
  sleep_hours: number;
  soreness_pain: string;
  special_context: string;
}

function checkinBlock(checkin: CheckIn | null): string {
  if (!checkin) return "El atleta no llenó el check-in de hoy — usa el historial reciente como referencia.";
  return `
Check-in de HOY que el atleta acaba de llenar — tiene prioridad sobre el historial para ajustar la
sesión de hoy específicamente (puede subir, mantener o bajar volumen/intensidad respecto al plan base):
- Energía hoy (1-5, 1=muy bajo): ${checkin.energy}
- Horas de sueño anoche: ${checkin.sleep_hours}
- Dolor/molestias ahora mismo: ${checkin.soreness_pain || "ninguna reportada"}
- Contexto especial de hoy (tiempo disponible, eventos, etc.): ${checkin.special_context || "ninguno"}
`.trim();
}

interface BlockDaySession {
  day_offset: number;
  type: string;
  summary: string;
}

interface BlockWeek {
  week_number: number;
  label: string;
  sessions: BlockDaySession[];
}

// Yoga is instructor-led at the gym — the engine doesn't script the class itself,
// it just registers that it happened (or not) for fatigue/mobility context.
function yogaPlaceholderExercise(daySummary: string | undefined): PlannedSession["exercises"][number] {
  return {
    name: "Clase de yoga con instructora",
    notes:
      daySummary ??
      "Sesión guiada en el gimnasio. El motor no programa el contenido; solo la registra como recuperación activa/movilidad para efectos de fatiga del bloque.",
  };
}

export async function POST(request: Request) {
  const today = todayISO();
  const body = await request.json().catch(() => ({}));
  const checkin: CheckIn | null = body?.checkin ?? null;

  const { data: block } = await supabase
    .from("blocks")
    .select("*")
    .eq("status", "active")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (!block) {
    return NextResponse.json(
      { error: "No hay un bloque activo. Genera uno primero en /block." },
      { status: 400 }
    );
  }

  const { data: profile } = await supabase
    .from("athlete_profile")
    .select("data")
    .order("updated_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  const twoWeeksAgo = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)
    .toISOString()
    .slice(0, 10);

  const { data: recentLogs } = await supabase
    .from("session_logs")
    .select("*, sessions(date, type, week_number, planned_exercises)")
    .gte("created_at", twoWeeksAgo)
    .order("created_at", { ascending: false });

  // Diff two date-only strings (both parsed as UTC midnight) so this is immune
  // to server timezone — only `today` (already in the athlete's timezone) matters.
  const daysIntoBlock = Math.floor(
    (Date.parse(today) - Date.parse(block.start_date)) / (24 * 60 * 60 * 1000)
  );
  const dayOffset = daysIntoBlock + 1;
  const weekNumber = Math.min(4, Math.floor(daysIntoBlock / 7) + 1);

  const weeks: BlockWeek[] = block.raw_plan?.weeks ?? [];
  const plannedDay = weeks
    .flatMap((w) => w.sessions.map((s) => ({ ...s, week_number: w.week_number })))
    .find((s) => s.day_offset === dayOffset);

  let planned: PlannedSession;

  if (plannedDay?.type === "yoga") {
    // Yoga itself is instructor-led — never scripted. But every yoga day also
    // gets a short Kettlebell Flow / mobility-strength-endurance complement
    // generated by the engine (athlete request: standing structural rule, not
    // a one-off — covers both "went to class, want more" and "missed class").
    const prompt = `
Hoy (${today}, día ${dayOffset}, semana ${plannedDay.week_number}) es un día de yoga con instructora
según el bloque activo: ${plannedDay.summary}

La yoga NO se programa (es instructor-led). Genera SOLO un complemento corto de Kettlebell Flow /
movilidad-fuerza-resistencia de 15-25 minutos para este mismo día. Es un complemento de baja-media
fatiga (no debe competir con los días de fuerza pesada), enfocado en desarrollar capacidad atlética:
coordinación, control corporal, movilidad, resistencia, fuerza ligera. Prioriza movimientos de la
progresión de kettlebell que el atleta quiere desarrollar (Turkish Get-Up, carries, flows, windmills,
etc. según su nivel — empieza simple si es de las primeras veces) y sus áreas de debilidad (tobillos,
unilateral, core). Funciona también como el entrenamiento principal del día si el atleta se pierde la
clase de yoga.

${checkinBlock(checkin)}

Perfil del atleta (JSON):
${JSON.stringify(profile?.data ?? {}, null, 2)}

Logs de los últimos 14 días (RPE, dolor, sueño, rendimiento real):
${JSON.stringify(recentLogs ?? [], null, 2)}

Responde SOLO con un JSON con esta forma exacta (3-5 ejercicios):
{
  "exercises": [{ "name": string, "sets": number, "reps": string, "notes": string }],
  "justification": string
}
`.trim();

    const raw = await askEngine(prompt);
    const kbFlow = parseJsonResponse<{
      exercises: PlannedSession["exercises"];
      justification: string;
    }>(raw);

    planned = {
      type: "yoga",
      week_number: plannedDay.week_number,
      exercises: [yogaPlaceholderExercise(plannedDay.summary), ...kbFlow.exercises],
      justification: `Día de yoga con instructora (no se programa). Complemento de Kettlebell Flow generado para hoy: ${kbFlow.justification}`,
    };
  } else {
    const prompt = `
Genera la sesión de entrenamiento de HOY (${today}) para este atleta.

${
  plannedDay
    ? `El bloque activo indica que hoy (día ${dayOffset}, semana ${plannedDay.week_number}) es una sesión de tipo "${plannedDay.type}": ${plannedDay.summary}`
    : `No hay un día exacto definido en el bloque para hoy; usa el contexto general del bloque y la semana ${weekNumber}.`
}

${checkinBlock(checkin)}

Perfil del atleta (JSON):
${JSON.stringify(profile?.data ?? {}, null, 2)}

Bloque activo completo (inició ${block.start_date}):
${JSON.stringify(block.raw_plan ?? {}, null, 2)}

Logs de los últimos 14 días (RPE, dolor, sueño, rendimiento real):
${JSON.stringify(recentLogs ?? [], null, 2)}

Genera el detalle de ejercicios SOLO si el tipo de sesión es "fuerza" u "running" (running puede llevar
indicaciones de ritmo/atención articular, no una lista de ejercicios). Responde SOLO con un JSON con
esta forma exacta:
{
  "type": "fuerza" | "running" | "otro",
  "week_number": number,
  "exercises": [{ "name": string, "sets": number, "reps": string, "notes": string }],
  "justification": string
}
`.trim();

    const raw = await askEngine(prompt);
    planned = parseJsonResponse<PlannedSession>(raw);
  }

  const { data: session, error } = await supabase
    .from("sessions")
    .insert({
      block_id: block.id,
      date: today,
      week_number: planned.week_number,
      type: planned.type,
      title: defaultTitleFor(planned.type),
      planned_exercises: planned.exercises,
      justification: planned.justification,
      status: "planned",
      checkin,
    })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json(session);
}

export async function GET() {
  const today = todayISO();
  const { data, error } = await supabase
    .from("sessions")
    .select("*")
    .eq("date", today)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
  return NextResponse.json(data);
}

function defaultTitleFor(type: string): string {
  switch (type) {
    case "fuerza":
      return "Fuerza del día";
    case "running":
      return "Running";
    case "yoga":
      return "Yoga + Kettlebell Flow";
    default:
      return "Sesión del día";
  }
}

// Rename the day's session — purely cosmetic, doesn't affect engine logic.
export async function PATCH(request: Request) {
  const { session_id, title } = await request.json();
  if (!session_id || !title) {
    return NextResponse.json({ error: "session_id and title are required" }, { status: 400 });
  }
  const { data, error } = await supabase
    .from("sessions")
    .update({ title })
    .eq("id", session_id)
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
  return NextResponse.json(data);
}
